# Stage 1: build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln ./
COPY backend/*.csproj ./backend/
RUN dotnet restore

COPY backend/. ./backend
WORKDIR /app/backend

RUN dotnet publish -c Release -o /app/publish

# Stage 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./

EXPOSE 5134

CMD ["dotnet", "Backend.dll"]
