FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY *.sln ./
COPY src/*.csproj ./src/

RUN dotnet restore ./backend.sln

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY src/. ./src/

COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

WORKDIR /app/src

EXPOSE 5134

CMD ["/app/entrypoint.sh"]