# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - kanban

on:
  push:
    branches:
      - pure-asp-net
  workflow_dispatch:

env:
  SOLUTION_FILE: AspNetFinalProject.sln
  PROJECT_FILE: AspNetFinalProject/AspNetFinalProject.csproj
  PUBLISH_DIR: publish
  DOTNET_VERSION: 9.x

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE }} -c Release --no-restore

      - name: Publish Web
        run: dotnet publish ${{ env.PROJECT_FILE }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-publish
          path: ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A846EC1FD7643E6945EEDD6BFDC666C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6E077837E2E84A0F8F147111539AA332 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_368CDB45D15B445BBAEEEC2CD9805291 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: kanban
          slot-name: Production
          package: ./publish
          